title: Loki senpai
description: "just a freak"
author:
  name: "Lokisenapai"
  email: "ghoul@hi2.in"
  url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - glitch-jekyll
  - jekyll-admin

# Custom variables
owner : "Loki senpai"
year : "2022"
